name: AndroidBuild

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4.1.0

      - name: Setup Java JDK 17
        uses: actions/setup-java@v3.13.0
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Grant execute permissions for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run : ./gradlew build

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.3

        with:
          name: dsTemplate.apk
          path: app/build/outputs/apk/debug/app-debug.apk