name: Run tests

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Java JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: gradle

      - name: Grant execute permissions for Gradle wrapper
        run: chmod +x gradlew

      # Run unit tests
      - name: Run Unit Tests
        run: ./gradlew clean test

      # Run instrumentation tests
      - name: Run Instrumentation Tests
        run: ./gradlew connectedAndroidTest
